### ISSUE TITLE
Transfer to emacs-helm organization?

### ISSUE THREAD

**Issue by jcs090218** [jcs-legacy/helm-file-preview#2]
Hi, @thierryvolpiatto

Would you mind if I transfer all my helm packages (3) to the organization `emacs-helm`?

* [helm-file-preview](https://github.com/jcs-elpa/helm-file-preview) (this) - Alternative to [helm-swoop](https://github.com/emacsorphanage/helm-swoop) and [helm-follow-mode]().
* [helm-fuzzy](https://github.com/jcs-elpa/helm-fuzzy) - Alternative to [helm-flx](https://github.com/PythonNut/helm-flx), and `helm` built-in fuzzy.
* [helm-searcher](https://github.com/jcs-elpa/helm-searcher) - helm interface for package [searcher](https://github.com/jcs-elpa/searcher)

Let me know what you think! Thanks!

**Comment by thierryvolpiatto** [comment]
Hi Jen-Chieh,

Jen-Chieh Shen <notifications@github.com> writes:

> Hi, @thierryvolpiatto
>
> Would you mind if I transfer all my helm packages (3) to the organization emacs-helm?

I am generally in favor of moving helm packages to emacs-helm
organisation, however I disagree with some packages that create
confusion for most helm users (specially new users not aware of helm
capabilities).
 
>   • helm-file-preview (this) - Alternative to helm-swoop and helm-follow-mode.

This is provided out of the box with Helm itself, why users would have
to install this?

>   • helm-fuzzy - Alternative to helm-flx, and helm built-in fuzzy.

We have now two ways to provide fuzzy matching, the helm native
fuzzy-matching and the completion-style flex (or helm-flex if flex not
available). I never stick with flx package and its variant because its
unnecessary complexity and slowness on large set of candidates even if
it is smarter in some use cases, thus AFAIK flx is no more maintained.
   
>   • helm-searcher - helm interface for package searcher

Don't know this one, looks nice except that (IIUC) it is using flx.
Is it possible to not use flx (or optional)?
 
Thanks.

-- 
Thierry

**Comment by jcs090218** [comment]
> I am generally in favor of moving helm packages to emacs-helm
organisation, however I disagree with some packages that create
confusion for most helm users (specially new users not aware of helm
capabilities).

Got it! I see your point here.

> This is provided out of the box with Helm itself, why users would have
to install this?

Sorry that I have created this package while I don't fully understand what `helm` can do! You are right about this package, it became meaningless once you properly customize `helm` itself.

> We have now two ways to provide fuzzy matching, the helm native
fuzzy-matching and the completion-style flex (or helm-flex if flex not
available). I never stick with flx package and its variant because its
unnecessary complexity and slowness on large set of candidates even if
it is smarter in some use cases, thus AFAIK flx is no more maintained.

hmm.. It seems like author of `flx` consider the package itself is stable and not unmaintained? But I do agree the slowness from flx. It is fine if you don't feel like this repository should be under `emacs-helm` organization!

> Don't know this one, looks nice except that (IIUC) it is using flx.
Is it possible to not use flx (or optional)?

Yes! `flx` is totally optional in package [searcher](https://github.com/jcs-elpa/searcher)!

---

Thanks for letting me know your thoughts!

**Comment by thierryvolpiatto** [comment]
Jen-Chieh Shen <notifications@github.com> writes:

>     I am generally in favor of moving helm packages to emacs-helm
>     organisation, however I disagree with some packages that create
>     confusion for most helm users (specially new users not aware of helm
>     capabilities).
>    
> Got it! I see your point here.
>
>     This is provided out of the box with Helm itself, why users would have
>     to install this?
>    
> Sorry that I have created this package while I don't fully understand what helm can do! You are right about this package, it became meaningless once you properly customize helm itself.
>
>     We have now two ways to provide fuzzy matching, the helm native
>     fuzzy-matching and the completion-style flex (or helm-flex if flex not
>     available). I never stick with flx package and its variant because its
>     unnecessary complexity and slowness on large set of candidates even if
>     it is smarter in some use cases, thus AFAIK flx is no more maintained.
>    
> hmm.. It seems like author of flx consider the package itself is stable and not unmaintained? But I do agree the slowness from flx. It is fine if you don't feel like this repository should
> be under emacs-helm organization!
>
>     Don't know this one, looks nice except that (IIUC) it is using flx.
>     Is it possible to not use flx (or optional)?
>    
> Yes! flx is totally optional in package searcher!

Ok good. I am going to add you to emacs-helm, when you receive
invitation (if it had not changed, last time it was like this) accept
and then you should be able to push your package to emacs-helm.

Thanks.

-- 
Thierry

**Comment by jcs090218** [comment]
> Ok good. I am going to add you to emacs-helm, when you receive
invitation (if it had not changed, last time it was like this) accept
and then you should be able to push your package to emacs-helm.

Cool! Thanks! 

Just to confirm, which package you allowed me to transfer to organization emacs-helm?

- [x] helm-searcher
- [ ] helm-file-preview
- [ ] helm-fuzzy

Very appreciated! ;)

**Comment by thierryvolpiatto** [comment]
Jen-Chieh Shen <notifications@github.com> writes:

>     Ok good. I am going to add you to emacs-helm, when you receive
>     invitation (if it had not changed, last time it was like this) accept
>     and then you should be able to push your package to emacs-helm.
>    
> Cool! Thanks!
>
> Just to confirm, which package you allowed me to transfer to organization emacs-helm?

helm-searcher.

>   • [X] helm-searcher
>   • [ ] helm-file-preview
>   • [ ] helm-fuzzy
>
> Very appreciated! ;)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

**Comment by jcs090218** [comment]
Thank you very much! :D
