### ISSUE TITLE
Error happening:   custom-initialize-reset: No applicable method: project-root , nil

### ISSUE THREAD

**Issue by jeff-phil** [jcs-legacy/helm-file-preview#4]
The latest commit, b6108fa, and release is causing the following error:

     custom-initialize-reset: No applicable method: project-root , nil

This happens with any helm command, such as `C-h f' to open help, is used.  After error happens, the helm command is stopped.

Current Settings:
```
(use-package helm-file-preview
  :config
  (helm-file-preview-mode 1))
(setq helm-file-preview-only-when-line-numbers nil)
(setq helm-file-preview-preview-only t)

```
GNU Emacs 28.1 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95))
 of 2022-05-11

**Comment by jcs090218** [comment]
Would `(require 'project)` helps? I think this is the missing piece.

**Comment by jeff-phil** [comment]
Sorry, no, adding `(require 'project)` does not help, same error.

**Comment by jcs090218** [comment]
Does function `project-root` exist? 😕 Try eval the code below and post the result here.

```elisp
(message "%s" (fboundp #'project-root))
```

It should simply return `t`, if it does not exists; then `nil`.

**Comment by jeff-phil** [comment]
If I open a file under project control, then helm commands work.

You should also be able to reproduce by opening `*scratch*` buffer which should not be in a project, and doing any command with helm interaction (M-x, help, etc.).

As well, I get same error if I go to `*scratch*` and do an eval on `(project-root (project-current))` because the buffer is not in a project.  But in a project file it returns the project folder, which is expected.

Looking at the commit b6108fa, previously line 108: `(cdr (project-current))` returns `nil` when not in a project. 

But new line 113: `(project-root (project-current))` instead fails on error, and stops.

**Comment by jcs090218** [comment]
Can you try branch `fix/project-root` #5? I have wrapped it with `ignore-errors` so it should return just fine like the previous one `(cdr ...`.

**Comment by jeff-phil** [comment]
Yes, that's the fix.  Thanks!

**Comment by jcs090218** [comment]
Great! 🎉  Thanks for the bug report! :)

Sorry, it took this long to resolve! 😅
